name: on-push

on:
  push:
    branches: '**'
jobs:
  rust-workflow:
    uses: affinidi/pipeline-rust/.github/workflows/on-push.yaml@fix/release-step-on-branch
    secrets: inherit
    with:
      auditIgnore: "RUSTSEC-2022-0040,RUSTSEC-2023-0071"
      publish_dry_run: false        